### ISSUE TITLE
LackOfCohesionInMethods (LCOM) implementieren

### ISSUE THREAD

**Issue by X1999-1** [sse-labs/fachproject-metrics-framework#12]
LCOM misst die Ähnlichkeit von Methoden in einer Klasse, indem die Anzahl der Methodenpaare, dessen Methoden auf mindestens ein gleiches Attribut zugreifen, von der Anzahl der Methodenpaare, dessen Methoden ausschließlich auf unterschiedliche Attribute zugreifen, subtrahiert wird. Im Falle eines negativen Ergebnisses ist der LCOM-Wert 0.

**Comment by MinjoyF** [comment]
oder LCOM wird Zur Messung des Kohäsionsgrads einer Klasse benutzt. Dafür bildet sie die Differenz aus der Anzahl der Methodenpaaren, die gemeinsame Variable verwenden, und der Anzahl der Methoden Paare, die über disjunkte Variablensätze verfügen

**Comment by X1999-1** [comment]
> oder LCOM wird Zur Messung des Kohäsionsgrads einer Klasse benutzt. Dafür bildet sie die Differenz aus der Anzahl der Methodenpaaren, die gemeinsame Variable verwenden, und der Anzahl der Methoden Paare, die über disjunkte Variablensätze verfügen

Danke für den Kommentar. In der Tat habe ich an zwei Stellen "Methoden" statt "Methodenpaare" geschrieben, sodass meine ursprüngliche Formulierung nicht ganz korrekt war. Ich habe das mittlerweile geändert. Die Ergänzung mit der Kohäsion finde ich auch gut. Ansonsten denke ich, hast du auch das inhaltlich geschrieben, was ich geschrieben habe, nur anders formuliert.

**Comment by MehdiHa96** [comment]
Wäre cool hier einen Link zu einem Paper mit formaler Definition zu haben, genauso wie im Code. Der weist ganz klar darauf hin, dass es sich um LCOM2 von C&K handelt.
