### ISSUE TITLE
Provide an interface for analyzing classes

### ISSUE THREAD

**Issue by johannesduesing** [sse-labs/fachproject-metrics-framework#25]
**Describe the problem**
We currently have dedicated interfaces for analyzing a single File and each method inside a file, but not for analyzing classes. However, our last meeting revealed that such an interface would be helpful for some metrics. This was suggested by @skyfly18 

**Describe the solution you'd like**
Provide an interface that extends `SingleFileAnalysis` and allows analysis of classes / types.

**Comment by skyfly18** [comment]
projectClassFiles ist doch private und das intellij dies anzeigt doch ein bug wo drüber wir geredet haben.
Denn die Funktion lässt sich nicht kompilieren, mit denn Fehler meldung:
 value projectClassFiles is not a member of org.opalj.br.analyses.Project[java.net.URL]
possible cause: maybe a semicolon is missing before `value projectClassFiles'?
      .projectClassFiles


Wäre nicht allClassFiles nicht besser?

**Comment by johannesduesing** [comment]
Sehr guter Punkt, eben noch drüber gesprochen und direkt wieder vergessen...Sorry dafür. Hab den Fehler behoben und direkt in develop gepusht, sollte also jetzt verfügbar sein (Commit 64d595ecd3e031e8e1baa6b82e63218a416f643c). Falls noch was nicht stimmen sollte das Issue gerne wieder aufmachen!

**Comment by skyfly18** [comment]
Ich bekomme vom ObjectType nicht wieder zur ClassFile type. Da ObjectType keine funktion bietet um wieder zur ClassFile oder Methoden zubekommen, wäre es besser eine Analysis für Type und ein für Klassen zuhaben.
[](https://www.opal-project.de/library/api/SNAPSHOT/org/opalj/br/ObjectType.html)

**Comment by johannesduesing** [comment]
Ich habe das ganze jetzt zurückgeändert in eine `ClassFileAnalysis`. Meiner Meinung nach sollte das ausreichen, da man auf jedem `ClassFile` einfach `.thisType()` nutzen kann, um den entsprechenden `ObjectType` zu bekommen (es gibt immer genau einen `ObjectType` pro `ClassFile`). Ich habe dafür jetzt einen PR angelegt (siehe #28) und Sie als Reviewer vermerkt. Gucken sie sich das gerne nocheinmal in Ruhe an, und geben Sie mir Review-Feedback in dem Pull Request falls etwas nicht passen sollte 👍 Wenn die Änderungen so in Ordnung sind bitte einmal eine "Approve"-Review abgeben, dann merge ich das in `develop` und schließe dieses Issue.
