### ISSUE TITLE
Bei der zurück gabe von List kein Array möglich

### ISSUE THREAD

**Issue by skyfly18** [sse-labs/fachproject-metrics-framework#27]
Bei zurück gabe List damit die Ergebnisse ausgeben werden können, ist es nicht möglich ein Array, ArrayList von MetricValue zu übergeben.

**Comment by skyfly18** [comment]
Was nicht funktioniert ist wenn ich eine Ausgabe unbekannte größe haben will.

```
var rlist = new ListBuffer[MetricValue]
rlist +=MetricValue("test", "test.a", 42.0)
List(rlist)
```

Gerade wenn man eine unbekannte anzahl an Methoden einer Klasse analysiert und ein Ergebniss für jede Methode zurück geben will, geht das mit denn aktuellen interface nicht.

**Comment by johannesduesing** [comment]
Ah okay, ich verstehe das Problem.  Auch das sollte mit dem aktuellen Interface aber lösbar sein, indem Sie die `toList` Methode von `ListBuffer` verwenden. Folgendes funktioniert bei mir:
```
  val metricsBuffer = new ListBuffer[MetricValue]()

  val a = MetricValue("test", "test.a", 42.0)
  val b = MetricValue("test", "test.b", 3.14159)
  
  // Hier beliebig viele Metriken zum Buffer hinzufügen
  metricsBuffer += a
  metricsBuffer += b
    
  metricsBuffer.toList
```

**Comment by skyfly18** [comment]
Ok. Hab es jetzt am laufen bekommen.
