### ISSUE TITLE
MultiFileAnalysis - Namen der aktuellen jar-Datei verfügbar machen

### ISSUE THREAD

**Issue by PKTUDO** [sse-labs/fachproject-metrics-framework#30]
Ist es möglich bei der MultiFileAnalysis sich nicht nur das Verzeichnis, aus dem die .jar-Dateien stammen, anzeigen zu lassen, sondern auch den Namen der einzelnen .jar-Datei, die gerade von  produceAnalysisResultForJAR() untersucht wird?
Diese Information könnte man nutzen um bei der Differentiellenuntersuchung genau anzugeben auf welche beiden Dateien sich das Ergebnis bezieht. (z.Bsp für MetricValue(entityIdent,..)

**Comment by johannesduesing** [comment]
Ich habe eine Möglichkeit dafür implementiert und in PR #31 zusammengefasst. Bitte gucken Sie einmal drüber ob das so passt und verständlich ist. Wenn ja bitte ich um eine approving review, wenn nein bitte Fragen im PR stellen 🙂

**Comment by johannesduesing** [comment]
Closed with #31
