### ISSUE TITLE
Multifileanalysis csv-Ausgabe unsortiert

### ISSUE THREAD

**Issue by PKTUDO** [sse-labs/fachproject-metrics-framework#35]
Multifileanalysis csv-Ausgabe unsortiert
Differenzen werden nicht in der Reihenfolge in der csv-Datei geschrieben, in der sie berechnet, bzw. zurück an die aufrufende Methode gegeben wurden. Sortiert wären die Ergbenisse leichter erfassbar

Beispiel-csv:
"Path","Entity","ES_stability","ES_Removed","ES_Remained"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between: F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.1.jar and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-3.0.jar","0.7388888888888889","1.0","0.7388888888888889"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between: F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-1.0.jar and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.0.20020914.015953.jar","1.0","1.0","1.0"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between: F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.0.20020914.015953.jar and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.0.20020914.020746.jar","1.0","1.0","1.0"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between: F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.0.jar and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.1.1.jar","0.9540229885057472","1.0","0.9540229885057472"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between: F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.1.1.jar and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.1.jar","0.9625668449197861","1.0","0.9625668449197861"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between: F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-3.0.jar and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-3.1.jar","0.9533799533799534","1.0","0.9533799533799534"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between: F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-3.2.1.jar and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-3.2.2.jar","1.0","1.0","1.0"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between: F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.0.20020914.020858.jar and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.0.jar","0.4252421910366682","0.8765957446808511","0.48510638297872344"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between: F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-3.2.2.jar and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-3.2.jar","0.9782608695652174","1.0","0.9782608695652174"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between: F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.0.20020914.020746.jar and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-2.0.20020914.020858.jar","1.0","1.0","1.0"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between:  and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-1.0.jar","1.0","1.0","1.0"
"F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections","Difference between: F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-3.1.jar and F:\Uni\WS2122\Fachprojekt\jars\Commons-Collections\commons-collections-3.2.1.jar","0.9820627802690582","1.0","0.9820627802690582"

**Comment by johannesduesing** [comment]
Das Issue hier würde ich gerne erstmal schließen. Ich habe nochmal über den CSV-Ausgabealgorithmus geschaut: Da der die Ergebnisse ja pro Datei und dann pro Entity zusammenfasst, ist es eigentlich nicht möglich irgendeine Reihenfolge zu erhalten, sobald mehr als eine Analyse beteiligt ist. Und für den Einzellfall von nur einer beteiligten Analyse würde ich nur ungerne den Vorteil des Zusammenfassens aufgeben. Sortieren und Filtern kann man zur Not in einen Postprocessing Step auslagern.

Sollte das in der Evaluationsphase unerwartete Probleme machen, dann können wir das Issue hier gerne nochmal aufmachen.
